gunnery:
  build: .
  links:
    - db
  environment:
    DJANGO_SETTINGS_MODULE: "gunnery.settings.production"
    SECRET_KEY: "randomize_me"
    ADMIN_EMAIL: "admin@admin.local"
  ports:
    - "8080:8080"
db:
  image: postgres
  ports:
    - "5432:5432"
